# Generated by Django 3.1.1 on 2020-10-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_seed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Crop',
        ),
    ]
