# Generated by Django 3.1.1 on 2020-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20201002_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='price',
        ),
        migrations.AddField(
            model_name='crop',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
