# Generated by Django 3.1.1 on 2020-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20201002_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='pics')),
                ('slider1', models.ImageField(upload_to='pics')),
                ('slider2', models.ImageField(upload_to='pics')),
                ('slider3', models.ImageField(upload_to='pics')),
                ('slider4', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
